<!-- build:css -->
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/vendor/css/line-awesome.css">
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/vendor/css/swiper.min.css">
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/vendor/css/prism.css">
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/css/bootstrap-custom.css">
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/css/theme.css">
<!-- endbuild -->
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/css/custom.css">
<link rel="stylesheet" href="<?=base_url()?>/assets/marketspot/assets/css/rtl.css">